"""Link the IPC app to the Crystal Gallery cost model (single source of truth for the contract price).

Reads the priced bill (CGJED) from crystal-gallery-takeoff.html, the "Crystal Gallery 4D/5D" take-off
and cost model, and writes assets/js/crystal-gallery-costing.js, which the IPC app loads. The
Crystal Gallery main-contract BoQ, and so its contract sum, is built from that file on every load.

Usage:
  python3 tools/sync_costing.py            # regenerate from the costing branch (git ref below)
  python3 tools/sync_costing.py --check    # exit 1 if the committed file is out of date (used by tests/CI)
  python3 tools/sync_costing.py --source path/to/crystal-gallery-takeoff.html

Pricing rules mirror buildPlannerBoQ()/rollUp() in the cost model exactly:
  line base   = round(qty × rate)                 (JS Math.round)
  line amount = round(base × escalation factor)   (out-turn)
  contract sum = Σ line amounts (out-turn, excl. contingency reserve and VAT)
The cost model's contingency reserve (plannerContPct) is exported for reference only: it is the
employer's reserve, not part of the sum certified to the contractor.
"""
import argparse
import json
import math
import re
import subprocess
import sys
from pathlib import Path

COSTING_REF = "origin/claude/stoic-hypatia-456ykd"
COSTING_FILE = "crystal-gallery-takeoff.html"
OUT = Path("assets/js/crystal-gallery-costing.js")


def js_round(x):
    # JavaScript Math.round: halves round towards +infinity.
    return math.floor(x + 0.5)


def git(*args):
    return subprocess.run(["git", *args], check=True, capture_output=True, text=True).stdout


def load_source(path):
    if path:
        return Path(path).read_text(), {"file": str(path), "ref": None, "commit": None}
    git("fetch", "-q", "origin", COSTING_REF.split("/", 1)[1])
    html = git("show", f"{COSTING_REF}:{COSTING_FILE}")
    commit = git("rev-parse", COSTING_REF).strip()
    return html, {"file": COSTING_FILE, "ref": COSTING_REF.split("/", 1)[1], "commit": commit}


def parse(html):
    m = re.search(r"^const CGJED = (\[.*\]);\s*$", html, re.M)
    if not m:
        sys.exit("CGJED priced bill not found in the cost model — its format changed; update tools/sync_costing.py")
    rows = json.loads(m.group(1))
    basis = dict(re.findall(r"(\w+):'([^']*)'", re.search(r"^const CGJED_RATE_BASIS = \{(.*)\};\s*$", html, re.M).group(1)))
    basis.update(dict(re.findall(r'(\w+):"([^"]*)"', re.search(r"^const CGJED_RATE_BASIS = \{(.*)\};\s*$", html, re.M).group(1))))
    cont = float(re.search(r"plannerContPct:\s*([\d.]+)", html).group(1))
    vat = float(re.search(r"vatPct:\s*([\d.]+)", html).group(1))
    start = re.search(r"startDate:\s*'([\d-]+)'", html).group(1)
    return rows, basis, cont, vat, start


def build(html, src):
    rows, basis, cont, vat, start = parse(html)
    lines = []
    for code, desc, qty, unit, rate, esc, source, rate_key, es, ef in rows:
        base = js_round(qty * rate)
        amt = js_round(base * esc)
        lines.append({
            "code": code, "desc": desc, "qty": qty, "unit": unit, "baseRate": rate, "esc": esc,
            "baseAmt": base, "amt": amt,
            "src": "DRW" if source.startswith("Sheet 17") else "DER" if source.startswith("Derived") else "ALW",
            "source": source, "rateBasis": basis.get(rate_key, rate_key), "startDay": es, "finishDay": ef,
        })
    base_total = sum(l["baseAmt"] for l in lines)
    outturn = sum(l["amt"] for l in lines)
    return {
        "source": {**src, "title": "Crystal Gallery 4D/5D (take-off & 5D cost model)",
                   "artifact": "https://claude.ai/artifact/2tqcb27PQu8xh6TrKJ5qNM"},
        "constructionStart": start,
        "durationDays": max(l["finishDay"] for l in lines),
        "contingencyPct": cont,
        "vatPct": vat,
        "lines": lines,
        "totals": {
            "base": base_total,
            "outturn": outturn,  # = contract sum
            "contingency": round(outturn * cont / 100, 2),
            "withContingency": round(outturn * (1 + cont / 100), 2),
        },
    }


def render(data):
    body = json.dumps(data, indent=1, ensure_ascii=False)
    return (
        "/* GENERATED by tools/sync_costing.py — do not edit by hand.\n"
        " * Priced bill of the Crystal Gallery cost model (" + COSTING_FILE + "). The IPC app builds the\n"
        " * Crystal Gallery main-contract BoQ and contract sum from this file, so the two stay linked.\n"
        " * Re-run the script whenever the cost model changes; tests fail while they disagree. */\n"
        "(function (root) {\n  const data = " + body + ";\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = data;\n"
        "  else root.CG_COSTING = data;\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    html, src = load_source(a.source)
    data = build(html, src)
    out = render(data)
    if a.check:
        current = OUT.read_text() if OUT.exists() else ""
        # Compare the priced content only; the commit hash may differ if the costing branch was rebased without changes.
        strip = lambda s: re.sub(r'"(commit|ref|file)": [^\n]*\n', "", s)
        if strip(current) != strip(out):
            print(f"OUT OF DATE: {OUT} no longer matches {COSTING_FILE}. Run: python3 tools/sync_costing.py")
            sys.exit(1)
        print("in sync:", data["totals"])
        return
    OUT.write_text(out)
    t = data["totals"]
    print(f"wrote {OUT}: {len(data['lines'])} lines | base SAR {t['base']:,} | contract sum (out-turn) SAR {t['outturn']:,} "
          f"| +{data['contingencyPct']:g}% reserve SAR {t['withContingency']:,.0f} | source {src.get('commit') or src['file']}")


if __name__ == "__main__":
    main()
